### PR TITLE
Sprint 3 Mockups

### PR DESCRIPTION
**Pull request by Radu-Raicea**

### CODE REVIEW

**Comment by g-harel** [comment]
1. Since pinned messages are probably not going to be from one continuous conversation, what do y'all think of adding a separator in the UI when messages don't follow each other.

```
Message1
Message2
---
Message8
---
Message21
...
```

2. I think it might be better if the unpin buttons are more consistently placed. Right now, its position depends on the length of the outgoing message.

**Comment by g-harel** [comment]
3. I also don't like that the pin icon is so visible on the conversation UI. It almost looks like it's a button .. so if we aren't doing that, I think something more subtle might work better.

**Comment by g-harel** [comment]
4. For the nickname settings, how does it work when it's `default`? Is that the string inside the box? Would it be possible to add the editing box at the top where the name is written, I find it odd to have the same thing written twice on the same screen.

**Comment by shelbaz** [comment]
When its default its the normal name. It can also be when its blank string as well, doesnt matter. But the editing box at the top might be harder to implement which is why i just added it as a textbox on a new row.

**Review by shelbaz — APPROVED** [review]
Looks good to me !

**Comment by erinb90** [comment]
@g-harel 
1. Good point, having the bubbles look like the regular chat makes it look too continuous. We can either do separators like you said or keep the bubbles the way they look now. 

2. The unpin button was done in a hurry last sprint. We can fix both the look of it and the positioning. 

3. I was thinking to make the pin icon in the main convo be much smaller than the unpin button in the pinned message view. Instead of the icon we could alternatively write the word "pinned" on the message but that might take up too much space.

**Review by erinb90 — APPROVED** [review]
Looks good

**Pull request merged**
